### ISSUE TITLE
is it ready for production servers?

### ISSUE THREAD

**Issue by Smorted** [shura62/Neptune#3]
i will only use angel, auto click, aura .. are they good and ready for a production server?

**Comment by shura62** [comment]
The answer is no. I'm currently working on the first official release of Neptune, which will be stable and ready for Poggit. I don't feel like the project is enough stable to be used on production. While I work on the new update, I suggest you using Mockingbird as it is the most stable public anticheat I've seen so far.

**Comment by Smorted** [comment]
with the default values for the checks?
